apiVersion: v1
kind: Secret
metadata:
  name: microservice-secret
type: Opaque
stringData:
  my-secret.txt: |
    This is a sample secret text.
    It contains multiple lines of text.
    Secrets should be handled with care.

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-config
data:
  ROOT_RESPONSE: "Hello, World!"
  SECRETS_PATH: "/secrets/my-secret.txt"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: rafalskolasinski/microservice:python
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: microservice-config
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: microservice-secret
      terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  type: LoadBalancer
  selector:
    app: microservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
